# Generated by Django 4.1.7 on 2023-03-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_country_userprofile_languaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='languaje',
            new_name='language',
        ),
    ]
