# Generated by Django 4.1.7 on 2023-03-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_languaje_userprofile_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='adrress',
            new_name='address',
        ),
    ]
