# Generated by Django 4.1.7 on 2023-03-11 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(4300000000000000), django.core.validators.MaxValueValidator(4399999999999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('purple', 'purple'), ('blue', 'blue'), ('green', 'green'), ('orange', 'orange')], default='purple', max_length=7),
        ),
    ]
