# Generated by Django 4.1.7 on 2023-03-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_card_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='valid_date',
            field=models.CharField(default='%m/%y', max_length=40),
        ),
    ]
