# Generated by Django 4.1.7 on 2023-03-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0014_alter_card_color_alter_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='valid_date',
            field=models.DateTimeField(),
        ),
    ]
