# Generated by Django 4.1.7 on 2023-03-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0016_alter_card_valid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('purple', 'purple'), ('blue', 'blue'), ('green', 'green'), ('orange', 'orange')], default='purple', max_length=7),
        ),
        migrations.AlterField(
            model_name='card',
            name='valid_date',
            field=models.DateTimeField(default='mm/yy', max_length=5),
        ),
    ]
