# Generated by Django 4.1.7 on 2023-03-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_languaje_userprofile_language'),
        ('admin_settings', '0002_remove_languaje_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languaje',
            new_name='Language',
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name_plural': 'Languages'},
        ),
    ]
